const Database = require("better-sqlite3");
const db = new Database("local.db");

// 1. Create the 'partners' table (Added 'logo' column)
db.exec(`
  DROP TABLE IF EXISTS partners;
  CREATE TABLE partners (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    logo TEXT, 
    website TEXT,
    field TEXT,
    tier TEXT,
    headline TEXT,
    scope TEXT,
    terms TEXT,
    description TEXT,
    redemption_title TEXT,
    step_1_title TEXT,
    step_1_instruction TEXT,
    step_2_title TEXT,
    step_2_instruction TEXT,
    step_3_title TEXT,
    step_3_instruction TEXT,

    address TEXT,
    zip_code TEXT,
    phone TEXT,
    hours_mon_fri TEXT,
    hours_sat TEXT,
    hours_sun TEXT
  )
`);

// 2. The Data (Added 'logo' property)
const partners = [
    {
        name: "Mercury Drug",
        logo: "mercury.webp",
        website: "http://www.mercurydrug.com",
        field: "Health & Pharmacy",
        tier: "Silver",
        headline: "Priority Lane Access",
        scope: "Medicine Purchase",
        terms: "Valid at the Senior Citizen Priority lane only.",
        description:
            "The Philippines' leading trusted drugstore, ensuring safe and affordable medicines are always available in Cabuyao.",
        redemption_title: "Skip the Line",
        step_1_title: "Arrive",
        step_1_instruction: "Proceed to the Senior/PWD Lane.",
        step_2_title: "Scan",
        step_2_instruction: "Present your ElderKey QR code.",
        step_3_title: "Pay",
        step_3_instruction: "Complete your discounted transaction.",

        address: "National Highway, Brgy. Sala, Cabuyao",
        zip_code: "4025",
        phone: "(049) 531-2550",
        hours_mon_fri: "24 Hours",
        hours_sat: "24 Hours",
        hours_sun: "24 Hours",
    },
    {
        name: "First Cabuyao Hospital",
        logo: "first-cabuyao.webp",
        website: "https://www.fchmci.net",
        field: "Health & Pharmacy",
        tier: "Gold",
        headline: "10% OFF Lab Tests",
        scope: "Outpatient Diagnostics",
        terms: "Excludes doctor's professional fees and emergency room charges.",
        description:
            "A private medical center in Brgy. Sala committed to providing quality healthcare services to Laguna residents.",
        redemption_title: "Medical Perk",
        step_1_title: "Visit",
        step_1_instruction: "Go to the Laboratory Department.",
        step_2_title: "Verify",
        step_2_instruction: "Show your active Gold subscription.",
        step_3_title: "Discount",
        step_3_instruction: "The bill will be adjusted automatically.",

        address: "St. Francis Village, Brgy. Sala, Cabuyao",
        zip_code: "4025",
        phone: "(049) 544-5932",
        hours_mon_fri: "24 Hours",
        hours_sat: "24 Hours",
        hours_sun: "24 Hours",
    },
    {
        name: "Puregold",
        logo: "puregold.webp",
        website: "http://www.puregold.com.ph",
        field: "Shopping",
        tier: "Silver",
        headline: "Free Eco Bag",
        scope: "Grocery Purchase",
        terms: "Minimum spend of ₱1,000 single receipt.",
        description:
            "A favorite supermarket for Cabuyeños offering low prices and a wide variety of fresh goods and household items.",
        redemption_title: "Claim Item",
        step_1_title: "Shop",
        step_1_instruction: "Complete your grocery shopping.",
        step_2_title: "Cashier",
        step_2_instruction: "Present items at the checkout counter.",
        step_3_title: "Redeem",
        step_3_instruction: "Ask for your free ElderKey Eco Bag.",

        address: "National Highway, Brgy. Banlic, Cabuyao",
        zip_code: "4025",
        phone: "(049) 531-4388",
        hours_mon_fri: "8:00 AM - 9:00 PM",
        hours_sat: "8:00 AM - 9:00 PM",
        hours_sun: "8:00 AM - 8:00 PM",
    },
    {
        name: "Jollibee",
        logo: "jollibee.webp",
        website: "https://www.jollibee.com.ph",
        field: "Dining",
        tier: "Bronze",
        headline: "Free Peach Mango Pie",
        scope: "With Value Meal",
        terms: "Valid for dine-in and take-out only. Not valid for delivery.",
        description:
            "The country's #1 fast food chain, bringing joy to Filipino families with the famous Chickenjoy.",
        redemption_title: "Sweet Treat",
        step_1_title: "Order",
        step_1_instruction: "Purchase any Chickenjoy Value Meal.",
        step_2_title: "Claim",
        step_2_instruction: "Inform the crew you have an ElderKey perk.",
        step_3_title: "Enjoy",
        step_3_instruction: "Receive your free dessert.",

        address: "Cabuyao Bayan, J.P. Rizal St., Cabuyao",
        zip_code: "4025",
        phone: "(049) #87000",
        hours_mon_fri: "7:00 AM - 10:00 PM",
        hours_sat: "7:00 AM - 10:00 PM",
        hours_sun: "8:00 AM - 9:00 PM",
    },
    {
        name: "Cabuyao Water District",
        logo: "cabuyao-water.webp",
        website: null,
        field: "Services",
        tier: "Silver",
        headline: "Priority Payment",
        scope: "Bill Settlement",
        terms: "Account name must match the Senior Citizen ID name.",
        description:
            "The local water utility provider dedicated to supplying potable water to Cabuyao households.",
        redemption_title: "Priority Pass",
        step_1_title: "Enter",
        step_1_instruction: "Go to the payment center office.",
        step_2_title: "Queue",
        step_2_instruction: "Use the designated Senior Citizen lane.",
        step_3_title: "Pay",
        step_3_instruction: "Present bill and ElderKey ID.",

        address: "JP Rizal St., Brgy. Poblacion Uno, Cabuyao",
        zip_code: "4025",
        phone: "(049) 543-0366",
        hours_mon_fri: "8:00 AM - 5:00 PM",
        hours_sat: "Closed",
        hours_sun: "Closed",
    },
    {
        name: "Ospital ng Cabuyao",
        logo: "ospital-cabuyao.webp",
        website: null,
        field: "Health & Pharmacy",
        tier: "Bronze",
        headline: "Priority Admittance",
        scope: "OPD Consultations",
        terms: "Subject to doctor availability and triage protocols.",
        description:
            "The primary public hospital of the city, providing subsidized healthcare to the people of Cabuyao.",
        redemption_title: "Check In",
        step_1_title: "Triage",
        step_1_instruction: "Proceed to the Triage Area.",
        step_2_title: "Identify",
        step_2_instruction: "Show your ElderKey Digital ID.",
        step_3_title: "Wait",
        step_3_instruction: "Wait in the Priority Seating area.",

        address: "Brgy. San Isidro, Cabuyao",
        zip_code: "4025",
        phone: "(049) 545-7353",
        hours_mon_fri: "24 Hours",
        hours_sat: "24 Hours",
        hours_sun: "24 Hours",
    },
    {
        name: "WalterMart",
        logo: "waltermart.webp",
        website: "https://www.waltermart.com.ph",
        field: "Shopping",
        tier: "Gold",
        headline: "Free Parking (2 Hrs)",
        scope: "Parking Fee",
        terms: "Must present a receipt worth ₱500 from the supermarket.",
        description:
            "A community mall providing a convenient and safe shopping experience for the residents of Banlic and nearby areas.",
        redemption_title: "Car Perk",
        step_1_title: "Park",
        step_1_instruction: "Park your vehicle in the mall parking.",
        step_2_title: "Shop",
        step_2_instruction: "Shop at the supermarket.",
        step_3_title: "Validate",
        step_3_instruction: "Show receipt and app at the parking booth.",

        address: "National Highway, Brgy. Banlic, Cabuyao",
        zip_code: "4025",
        phone: "(049) 502-8888",
        hours_mon_fri: "9:00 AM - 9:00 PM",
        hours_sat: "9:00 AM - 9:00 PM",
        hours_sun: "9:00 AM - 9:00 PM",
    },
    {
        name: "Generika Drugstore",
        logo: "generika.webp",
        website: "http://www.generika.com.ph",
        field: "Health & Pharmacy",
        tier: "Bronze",
        headline: "5% OFF Generic",
        scope: "Maintenance Meds",
        terms: "Valid for generic brands only. Minimum purchase of ₱200.",
        description:
            "Providing quality affordable generic medicines to help seniors manage their health without breaking the bank.",
        redemption_title: "Save Money",
        step_1_title: "Select",
        step_1_instruction: "Choose your maintenance medicines.",
        step_2_title: "Cashier",
        step_2_instruction: "Go to the counter for payment.",
        step_3_title: "Scan",
        step_3_instruction: "Let the staff scan your discount QR.",

        address: "Brgy. Mamatid, Cabuyao",
        zip_code: "4025",
        phone: "0922-888-1234",
        hours_mon_fri: "7:00 AM - 8:00 PM",
        hours_sat: "7:00 AM - 8:00 PM",
        hours_sun: "8:00 AM - 6:00 PM",
    },
    {
        name: "MERALCO",
        logo: "meralco.webp",
        website: "http://www.meralco.com.ph",
        field: "Services",
        tier: "Silver",
        headline: "Concierge Assistance",
        scope: "Customer Service",
        terms: "For bill inquiries and new applications only.",
        description:
            "The premier electric distribution utility powering homes and businesses in Cabuyao.",
        redemption_title: "Get Help",
        step_1_title: "Visit",
        step_1_instruction: "Enter the Business Center.",
        step_2_title: "Signal",
        step_2_instruction: "Raise your hand for the floor manager.",
        step_3_title: "Assist",
        step_3_instruction: "An officer will assist you at your seat.",

        address: "National Highway, Brgy. Sala, Cabuyao",
        zip_code: "4025",
        phone: "16211",
        hours_mon_fri: "8:00 AM - 5:00 PM",
        hours_sat: "8:00 AM - 12:00 PM",
        hours_sun: "Closed",
    },
    {
        name: "EO Executive Optical",
        logo: "eo.webp",
        website: "https://eoexecutiveoptical.com",
        field: "Health & Pharmacy",
        tier: "Gold",
        headline: "Free Frame Cleaning",
        scope: "Eyeglass Care",
        terms: "Available walk-in. Deep cleaning and screw tightening included.",
        description:
            "Trusted optical shop offering expert eye checkups and a wide selection of branded frames.",
        redemption_title: "Eye Care",
        step_1_title: "Visit",
        step_1_instruction: "Go to the EO branch inside WalterMart.",
        step_2_title: "Request",
        step_2_instruction: "Ask for the 'ElderKey Eyeglass Care' service.",
        step_3_title: "Wait",
        step_3_instruction: "Wait 5-10 mins for cleaning to finish.",

        address: "2nd Level, WalterMart, Brgy. Banlic",
        zip_code: "4025",
        phone: "(049) 545-5555",
        hours_mon_fri: "10:00 AM - 9:00 PM",
        hours_sat: "10:00 AM - 9:00 PM",
        hours_sun: "10:00 AM - 9:00 PM",
    },
    {
        name: "Mang Inasal",
        logo: "mang-inasal.webp",
        website: "https://www.manginasal.com",
        field: "Dining",
        tier: "Bronze",
        headline: "Free Extra Rice",
        scope: "Chicken Inasal",
        terms: "Valid for PM1 or PM2 meals only. Dine-in only.",
        description:
            "Serving the Philippines' favorite distinctively Pinoy grilled chicken and unlimited rice.",
        redemption_title: "Eat More",
        step_1_title: "Order",
        step_1_instruction: "Order a Chicken Inasal meal.",
        step_2_title: "Request",
        step_2_instruction: "Request your free extra rice immediately.",
        step_3_title: "Verify",
        step_3_instruction: "Show your app to the server.",

        address: "Centro Mall, Brgy. Pulo, Cabuyao",
        zip_code: "4025",
        phone: "0917-123-9999",
        hours_mon_fri: "10:00 AM - 9:00 PM",
        hours_sat: "10:00 AM - 9:00 PM",
        hours_sun: "10:00 AM - 9:00 PM",
    },
    {
        name: "7-Eleven",
        logo: "7-11.webp",
        website: "https://www.7-eleven.com.ph",
        field: "Shopping",
        tier: "Bronze",
        headline: "Free Coffee Upsize",
        scope: "City Blends Coffee",
        terms: "Buy a Small cup, get a Medium cup.",
        description:
            "The world's largest convenience store chain, open 24/7 for your immediate needs.",
        redemption_title: "Drink Up",
        step_1_title: "Brew",
        step_1_instruction: "Select the Medium cup size.",
        step_2_title: "Counter",
        step_2_instruction: "Bring coffee to the cashier.",
        step_3_title: "Scan",
        step_3_instruction: "Scan ElderKey to pay the price of Small.",

        address: "Brgy. Niugan, Cabuyao",
        zip_code: "4025",
        phone: "(049) 531-1111",
        hours_mon_fri: "24 Hours",
        hours_sat: "24 Hours",
        hours_sun: "24 Hours",
    },
    {
        name: "Goldilocks",
        logo: "goldilocks.webp",
        website: "https://www.goldilocks.com.ph",
        field: "Dining",
        tier: "Silver",
        headline: "₱50 OFF Cakes",
        scope: "Greeting Cakes",
        terms: "Minimum purchase of 8' round cake.",
        description:
            "The Philippines' beloved bakeshop, part of every Filipino celebration for over 50 years.",
        redemption_title: "Cake Discount",
        step_1_title: "Choose",
        step_1_instruction: "Pick a Greeting Cake from the display.",
        step_2_title: "Order",
        step_2_instruction: "Place your order at the counter.",
        step_3_title: "Discount",
        step_3_instruction: "Present app to deduct ₱50 from bill.",

        address: "Checkpoint, Brgy. Paciano, Cabuyao",
        zip_code: "4025",
        phone: "(049) 888-1234",
        hours_mon_fri: "9:00 AM - 8:00 PM",
        hours_sat: "9:00 AM - 8:00 PM",
        hours_sun: "9:00 AM - 7:00 PM",
    },
    {
        name: "Cabuyao Public Market",
        logo: "cabuyao-market.webp",
        website: null,
        field: "Shopping",
        tier: "Bronze",
        headline: "Porter Assistance",
        scope: "Heavy Loads",
        terms: "Organized by the local market cooperative. Tipping is optional but encouraged.",
        description:
            "The heart of local trade in Cabuyao, offering fresh produce, meats, and dry goods at market prices.",
        redemption_title: "Help Hands",
        step_1_title: "Shop",
        step_1_instruction: "Buy your wet market goods.",
        step_2_title: "Call",
        step_2_instruction: "Signal a designated 'ElderKey Porter'.",
        step_3_title: "Assist",
        step_3_instruction: "Porter will carry bags to your tricycle.",

        address: "J.P. Rizal St., Cabuyao Poblacion",
        zip_code: "4025",
        phone: "N/A",
        hours_mon_fri: "5:00 AM - 7:00 PM",
        hours_sat: "5:00 AM - 7:00 PM",
        hours_sun: "5:00 AM - 12:00 PM",
    },
];

// 3. Prepare the insertion (Added 'logo')
const insert = db.prepare(`
  INSERT INTO partners (
    name, logo, website, field, tier, headline, scope, terms, description, 
    redemption_title, step_1_title, step_1_instruction, 
    step_2_title, step_2_instruction, step_3_title, step_3_instruction,
    address, zip_code, phone, hours_mon_fri, hours_sat, hours_sun
  ) VALUES (
    @name, @logo, @website, @field, @tier, @headline, @scope, @terms, @description, 
    @redemption_title, @step_1_title, @step_1_instruction, 
    @step_2_title, @step_2_instruction, @step_3_title, @step_3_instruction,
    @address, @zip_code, @phone, @hours_mon_fri, @hours_sat, @hours_sun
  )
`);

// 4. Run the transaction
const insertMany = db.transaction((partners) => {
    for (const partner of partners) insert.run(partner);
});

insertMany(partners);

console.log("Partners table updated with logo columns and seeded!");
